languange: python
python:
  - "3.7"

install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install coverage

script: 
  - ENV_FOR_DYNACONF=testing PYTHONPATH=$PYTHONPATH:$(pwd) coverage run -m pytest

after_success:
  - bash <(curl -s https://codecov.io/bash)

