language: python
python:
- '3.8'
jobs:
  include:
  - stage: Tests
    name: Run unit tests
    install:
    - python3 -m pip install -r requirements.txt
    - python3 -m pip install coverage
    script:
    - ENV_FOR_DYNACONF=testing PYTHONPATH=$PYTHONPATH:$(pwd) coverage run -m pytest
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: Deploy
    name: Deploy to Heroku
    if: branch = master
    script: skip
    deploy:
      provider: heroku
      app: fastapi-notes
      on:
        repo: exepirit/fastapi-notes
      api_key:
        secure: $HEROKU_TOKEN
